  /****************/
 /***** Enum *****/
/****************/
//[x, y, z]
//x = Type (Agent, inbound,... )
//y = Key (parameters, realtime,... )
//z = Item (item index)
var Agent =
{
    Parameters :
    {
        AgentId :           [0, 0, 0],
        Account :           [0, 0, 1], 
        Firstname :         [0, 0, 2],
        Lastname :          [0, 0, 3], 
        SiteId :            [0, 0, 4],
        Server :            [0, 0, 5],
        TeamId :            [0, 0, 6],
        PauseId :           [0, 0, 7],
        PauseDescription :  [0, 0, 8],
        Groupkey :          [0, 0, 9],
        Active :            [0, 0, 10],
		LoginDateTime :     [0, 0, 11],
		LoginDateTimeUtc :  [0, 0, 12],
		IpAddress :     	[0, 0, 13],
		Extension :  		[0, 0, 14]
    },
    Realtime : 
    {
        StatusIndex :			[0, 1, 0],
        Status :                [0, 1, 1], 
        StatusStartTime :       [0, 1, 2],
        VoiceState :            [0, 1, 3], 
        VoiceAvailable :        [0, 1, 4],
        ChatState :             [0, 1, 5],
        ChatAvailable :         [0, 1, 6],
        EmailState :            [0, 1, 7],
        EmailAvailable :        [0, 1, 8],
        ListCurrentContactId :  [0, 1, 9],
        ActiveContactId :       [0, 1, 10],
		PerQueWaiting :       	[0, 1, 11],
		PerQueAbandoned :       [0, 1, 12],
		PerQueProcessed :       [0, 1, 13],
		PerQueEnQueue: 			[0, 1, 14]
    },
    History : 
    {
        Undefined :             		[0, 2, 0],
        Pause :                 		[0, 2, 1], 
        Off :                   		[0, 2, 2],
        Waiting :               		[0, 2, 3], 
        Wrapup :                		[0, 2, 4],
        WrapupInbound :         		[0, 2, 5],
        WrapupOutbound :        		[0, 2, 6],
        WrapupEMail :           		[0, 2, 7],
        WrapupChat :            		[0, 2, 8],
        Online :                		[0, 2, 9],
        HandelingInbound :      		[0, 2, 10],
        HandelingOutbound :     		[0, 2, 11],
        HandelingEMail :        		[0, 2, 12],
        HandelingChat :         		[0, 2, 13],
        ContactHandled :              	[0, 2, 14],
        ContactInboundHandled :      	[0, 2, 15],
        ContactOutboundHandled :     	[0, 2, 16],
        ContactEMailHandled :        	[0, 2, 17],
        ContactChatHandled :         	[0, 2, 18],
        ContactMsgSend :        		[0, 2, 19],
		ContactMsgReceived :      		[0, 2, 20],
        UndefinedTime :         		[0, 2, 21],
        PauseTime :             		[0, 2, 22],
        OffTime :               		[0, 2, 23],
        WaitingTime :           		[0, 2, 24],
        WrapupStateTime :       		[0, 2, 25],
        WrapupInboundTime :     		[0, 2, 26],
        WrapupOutboundTime :    		[0, 2, 27],
        WrapupEMailTime :       		[0, 2, 28],
        WrapupChatTime :        		[0, 2, 29],
        OnlineTime :            		[0, 2, 30],
        HandelingInboundTime :  		[0, 2, 31],
        HandelingOutboundTime : 		[0, 2, 32],
        HandelingEMailTime :    		[0, 2, 33],
        HandelingChatTime :     		[0, 2, 34],
        ContactHandledTime:            	[0, 2, 35],
        ContactInboundHandledTime :     [0, 2, 36],
        ContactOutboundHandledTime :	[0, 2, 37],
        ContactEMailHandledTime :       [0, 2, 38],
        ContactChatHandledTime :        [0, 2, 39],
        Preview :       				[0, 2, 40],
        PreviewTime :        			[0, 2, 41],
		HistoryTimeGraph :      		[0, 2, 42]
    }, 
    Production : 
    {
        PositiveCount :     		[0, 3, 0],
        PositiveSum :       		[0, 3, 1],
        NegativeCount :     		[0, 3, 2],
        NegativeSum :       		[0, 3, 3],
        ArguedCount :    			[0, 3, 4],
        TotalQualified : 			[0, 3, 5],
        TotalNotQualified :  		[0, 3, 6],
		DialingActionTime :  		[0, 3, 7],
		DialingActionPosTime :  	[0, 3, 8],
		DialingActionNegTime :  	[0, 3, 9],
		DialingActionArgTime :  	[0, 3, 10],
		OnlineActionTime :  		[0, 3, 11],
		OnlineActionPosTime :  		[0, 3, 12],
		OnlineActionNegTime :  		[0, 3, 13],
		OnlineActionArgTime :  		[0, 3, 14],
		OnHoldActionTime :  		[0, 3, 15],
		OnHoldActionPosTime :  		[0, 3, 16],
		OnHoldActionNegTime :  		[0, 3, 17],
		OnHoldActionArgTime :  		[0, 3, 18],
		WrapUpActionTime :  		[0, 3, 19],
		WrapUpActionPosTime :  		[0, 3, 20],
		WrapUpActionNegTime :  		[0, 3, 21],
		WrapUpActionArgTime :		[0, 3, 22],
		CommunicationActionTime :  	[0, 3, 23],
		CommunicationActionPosTime :[0, 3, 24],
		CommunicationActionNegTime :[0, 3, 25],
		CommunicationActionArgTime :[0, 3, 26],
		WorkActionTime :  			[0, 3, 27],
		WorkActionPosTime :  		[0, 3, 28],
		WorkActionNegTime :  		[0, 3, 29],
		WorkActionArgTime :  		[0, 3, 30],
		CompletedContacts :  		[0, 3, 31],
		CompletedContactsTime :		[0, 3, 32],
		AvgArgComTime :  			[0, 3, 33],
		AvgArgWorkTime :  			[0, 3, 34],
		AvgPosComTime :  			[0, 3, 35],
		AvgPosWorkTime :  			[0, 3, 36],
		AvgNegComTime :  			[0, 3, 37],
		AvgNegWorkTime :  			[0, 3, 38],
        RatioTotQual_Tot :  		[0, 3, 39],
        RatioArg_Tot :      		[0, 3, 40],
        RatioArg_TotQual :  		[0, 3, 41],
        RatioPos_Tot :      		[0, 3, 42],
        RatioPos_TotQual :  		[0, 3, 43],
		RatioPos_Arg:				[0, 3, 44],
		RatioNeg_Tot:				[0, 3, 45],
		RatioNeg_TotQual:			[0, 3, 46],
		RationNeg_Arg:				[0, 3, 47],
		AvgPosValue:				[0, 3, 48],
		AvgNegValue:				[0, 3, 49],
		sys_Reset :  				[0, 3, 50],
		RatioTotQual_TotGraph :  	[0, 3, 51],
		RatioArg_TotQualGraph :  	[0, 3, 52],
		RatioPos_TotQualGraph :  	[0, 3, 53],
		RatioNeg_TotQualGraph :  	[0, 3, 54]

    },
    PeriodProduction : 
    {
        PositiveCount :     		[0, 4, 0],
        PositiveSum :       		[0, 4, 1],
        NegativeCount :     		[0, 4, 2],
        NegativeSum :       		[0, 4, 3],
        ArguedCount :    			[0, 4, 4],
        TotalQualified : 			[0, 4, 5],
        TotalNotQualified :  		[0, 4, 6],
		DialingActionTime :  		[0, 4, 7],
		DialingActionPosTime :  	[0, 4, 8],
		DialingActionNegTime :  	[0, 4, 9],
		DialingActionArgTime :  	[0, 4, 10],
		OnlineActionTime :  		[0, 4, 11],
		OnlineActionPosTime :  		[0, 4, 12],
		OnlineActionNegTime :  		[0, 4, 13],
		OnlineActionArgTime :  		[0, 4, 14],
		OnHoldActionTime :  		[0, 4, 15],
		OnHoldActionPosTime :  		[0, 4, 16],
		OnHoldActionNegTime :  		[0, 4, 17],
		OnHoldActionArgTime :  		[0, 4, 18],
		WrapUpActionTime :  		[0, 4, 19],
		WrapUpActionPosTime :  		[0, 4, 20],
		WrapUpActionNegTime :  		[0, 4, 21],
		WrapUpActionArgTime :		[0, 4, 22],
		CommunicationActionTime :  	[0, 4, 23],
		CommunicationActionPosTime :[0, 4, 24],
		CommunicationActionNegTime :[0, 4, 25],
		CommunicationActionArgTime :[0, 4, 26],
		WorkActionTime :  			[0, 4, 27],
		WorkActionPosTime :  		[0, 4, 28],
		WorkActionNegTime :  		[0, 4, 29],
		WorkActionArgTime :  		[0, 4, 30],
		CompletedContacts :  		[0, 4, 31],
		CompletedContactsTime :		[0, 4, 32],
		AvgArgComTime :  			[0, 4, 33],
		AvgArgWorkTime :  			[0, 4, 34],
		AvgPosComTime :  			[0, 4, 35],
		AvgPosWorkTime :  			[0, 4, 36],
		AvgNegComTime :  			[0, 4, 37],
		AvgNegWorkTime :  			[0, 4, 38],
        RatioTotQual_Tot :  		[0, 4, 39],
        RatioArg_Tot :      		[0, 4, 40],
        RatioArg_TotQual :  		[0, 4, 41],
        RatioPos_Tot :      		[0, 4, 42],
        RatioPos_TotQual :  		[0, 4, 43],
		RatioPos_Arg:				[0, 4, 44],
		RatioNeg_Tot:				[0, 4, 45],
		RatioNeg_TotQual:			[0, 4, 46],
		RationNeg_Arg:				[0, 4, 47],
		AvgPosValue:				[0, 4, 48],
		AvgNegValue:				[0, 4, 49],
		sys_Reset :  				[0, 4, 50],
		RatioTotQual_TotGraph :  	[0, 4, 51],
		RatioArg_TotQualGraph :  	[0, 4, 52],
		RatioPos_TotQualGraph :  	[0, 4, 53],
		RatioNeg_TotQualGraph :  	[0, 4, 54]

    }   	
};

var Inbound =
{
    Parameters :
    {
        Id :            [1, 0, 0],
        Description :   [1, 0, 1], 
        GroupKey :      [1, 0, 2],
        CampaignId :    [1, 0, 3],
        CampaignName :  [1, 0, 4],
		MediaType :  	[1, 0, 5],
		MediaTypeId :  	[1, 0, 6]
    },
    Realtime : 
    {
        ActiveContacts :        [1, 1, 0],
        SystemPreprocessing :   [1, 1, 1], 
		Closing :   			[1, 1, 2],
        Ivr :                   [1, 1, 3],
        Waiting :               [1, 1, 4], 
        Online :                [1, 1, 5],
        WrapUp :                [1, 1, 6],
        Overflowing :           [1, 1, 7],
		Transfer :           	[1, 1, 8],
		MaxQueueTime :          [1, 1, 9],
		AgentInReady  : 		[1, 1, 10],
        ContactMsgSend :        [1, 1, 11],
		ContactMsgReceived :    [1, 1, 12],
		RealTimeGraph :         [1, 1, 13]
    },
    History : 
    {
        Received :                  [1, 2, 0],
        ReceivedTime :              [1, 2, 1], 
        Closed :                    [1, 2, 2],
        ClosedTime :                [1, 2, 3], 
        EndInSystemProcessing :     [1, 2, 4],
        EndInSystemProcessingTime : [1, 2, 5],
        EndInIvr :                  [1, 2, 6],
        EndInIvrTime :              [1, 2, 7],
        IvrFinish :                 [1, 2, 8],
        IvrFinishTime :             [1, 2, 9],
        IvrAbandoned :              [1, 2, 10],
        IvrAbandonedTime :          [1, 2, 11],
        Abandoned :                 [1, 2, 12],
        AbandonedTime :             [1, 2, 13],
        HandledByAgent :            [1, 2, 14],
        HandledByAgentTime :        [1, 2, 15],
        OverflowedCount :           [1, 2, 16],
        OverflowedContact :         [1, 2, 17],
        Waiting :                   [1, 2, 18],
        WaitingTime :               [1, 2, 19],
        Direct :                    [1, 2, 20],
        DirectTime :                [1, 2, 21],
        Transfer :                  [1, 2, 22],
        TransferTime :              [1, 2, 23],
        ContactMsgSend :        	[1, 2, 24],
		ContactMsgReceived :    	[1, 2, 25],
        HistoryGraph :              [1, 2, 26]
    },
    Production : 
    {
        PositiveCount :     		[1, 3, 0],
        PositiveSum :       		[1, 3, 1],
        NegativeCount :     		[1, 3, 2],
        NegativeSum :       		[1, 3, 3],
        ArguedCount :    			[1, 3, 4],
        TotalQualified : 			[1, 3, 5],
        TotalNotQualified :  		[1, 3, 6],
		DialingActionTime :  		[1, 3, 7],
		DialingActionPosTime :  	[1, 3, 8],
		DialingActionNegTime :  	[1, 3, 9],
		DialingActionArgTime :  	[1, 3, 10],
		OnlineActionTime :  		[1, 3, 11],
		OnlineActionPosTime :  		[1, 3, 12],
		OnlineActionNegTime :  		[1, 3, 13],
		OnlineActionArgTime :  		[1, 3, 14],
		OnHoldActionTime :  		[1, 3, 15],
		OnHoldActionPosTime :  		[1, 3, 16],
		OnHoldActionNegTime :  		[1, 3, 17],
		OnHoldActionArgTime :  		[1, 3, 18],
		WrapUpActionTime :  		[1, 3, 19],
		WrapUpActionPosTime :  		[1, 3, 20],
		WrapUpActionNegTime :  		[1, 3, 21],
		WrapUpActionArgTime :		[1, 3, 22],
		CommunicationActionTime :  	[1, 3, 23],
		CommunicationActionPosTime :[1, 3, 24],
		CommunicationActionNegTime :[1, 3, 25],
		CommunicationActionArgTime :[1, 3, 26],
		WorkActionTime :  			[1, 3, 27],
		WorkActionPosTime :  		[1, 3, 28],
		WorkActionNegTime :  		[1, 3, 29],
		WorkActionArgTime :  		[1, 3, 30],
		CompletedContacts :  		[1, 3, 31],
		CompletedContactsTime :		[1, 3, 32],
		AvgArgComTime :  			[1, 3, 33],
		AvgArgWorkTime :  			[1, 3, 34],
		AvgPosComTime :  			[1, 3, 35],
		AvgPosWorkTime :  			[1, 3, 36],
		AvgNegComTime :  			[1, 3, 37],
		AvgNegWorkTime :  			[1, 3, 38],
        RatioTotQual_Tot :  		[1, 3, 39],
        RatioArg_Tot :      		[1, 3, 40],
        RatioArg_TotQual :  		[1, 3, 41],
        RatioPos_Tot :      		[1, 3, 42],
        RatioPos_TotQual :  		[1, 3, 43],
		RatioPos_Arg:				[1, 3, 44],
		RatioNeg_Tot:				[1, 3, 45],
		RatioNeg_TotQual:			[1, 3, 46],
		RationNeg_Arg:				[1, 3, 47],
		AvgPosValue:				[1, 3, 48],
		AvgNegValue:				[1, 3, 49],
		sys_Reset :  				[1, 3, 50],
		RatioTotQual_TotGraph :  	[1, 3, 51],
		RatioArg_TotQualGraph :  	[1, 3, 52],
		RatioPos_TotQualGraph :  	[1, 3, 53],
		RatioNeg_TotQualGraph :  	[1, 3, 54]

    },
    PeriodProduction : 
    {
        PositiveCount :     		[1, 4, 0],
        PositiveSum :       		[1, 4, 1],
        NegativeCount :     		[1, 4, 2],
        NegativeSum :       		[1, 4, 3],
        ArguedCount :    			[1, 4, 4],
        TotalQualified : 			[1, 4, 5],
        TotalNotQualified :  		[1, 4, 6],
		DialingActionTime :  		[1, 4, 7],
		DialingActionPosTime :  	[1, 4, 8],
		DialingActionNegTime :  	[1, 4, 9],
		DialingActionArgTime :  	[1, 4, 10],
		OnlineActionTime :  		[1, 4, 11],
		OnlineActionPosTime :  		[1, 4, 12],
		OnlineActionNegTime :  		[1, 4, 13],
		OnlineActionArgTime :  		[1, 4, 14],
		OnHoldActionTime :  		[1, 4, 15],
		OnHoldActionPosTime :  		[1, 4, 16],
		OnHoldActionNegTime :  		[1, 4, 17],
		OnHoldActionArgTime :  		[1, 4, 18],
		WrapUpActionTime :  		[1, 4, 19],
		WrapUpActionPosTime :  		[1, 4, 20],
		WrapUpActionNegTime :  		[1, 4, 21],
		WrapUpActionArgTime :		[1, 4, 22],
		CommunicationActionTime :  	[1, 4, 23],
		CommunicationActionPosTime :[1, 4, 24],
		CommunicationActionNegTime :[1, 4, 25],
		CommunicationActionArgTime :[1, 4, 26],
		WorkActionTime :  			[1, 4, 27],
		WorkActionPosTime :  		[1, 4, 28],
		WorkActionNegTime :  		[1, 4, 29],
		WorkActionArgTime :  		[1, 4, 30],
		CompletedContacts :  		[1, 4, 31],
		CompletedContactsTime :		[1, 4, 32],
		AvgArgComTime :  			[1, 4, 33],
		AvgArgWorkTime :  			[1, 4, 34],
		AvgPosComTime :  			[1, 4, 35],
		AvgPosWorkTime :  			[1, 4, 36],
		AvgNegComTime :  			[1, 4, 37],
		AvgNegWorkTime :  			[1, 4, 38],
        RatioTotQual_Tot :  		[1, 4, 39],
        RatioArg_Tot :      		[1, 4, 40],
        RatioArg_TotQual :  		[1, 4, 41],
        RatioPos_Tot :      		[1, 4, 42],
        RatioPos_TotQual :  		[1, 4, 43],
		RatioPos_Arg:				[1, 4, 44],
		RatioNeg_Tot:				[1, 4, 45],
		RatioNeg_TotQual:			[1, 4, 46],
		RationNeg_Arg:				[1, 4, 47],
		AvgPosValue:				[1, 4, 48],
		AvgNegValue:				[1, 4, 49],
		sys_Reset :  				[1, 4, 50],
		RatioTotQual_TotGraph :  	[1, 4, 51],
		RatioArg_TotQualGraph :  	[1, 4, 52],
		RatioPos_TotQualGraph :  	[1, 4, 53],
		RatioNeg_TotQualGraph :  	[1, 4, 54]

    }   		
};

var Outbound =
{
    Parameters :
    {
        Mode :          [2, 0, 0],
        Id :            [2, 0, 1], 
        Description :   [2, 0, 2],
        GroupKey :      [2, 0, 3], 
        CampaignId :    [2, 0, 4],
        CampaignName :  [2, 0, 5],
		MediaType :  	[2, 0, 6],
		MediaTypeId :  	[2, 0, 7]
    },
    Realtime : 
    {
        SystemPreprocessing :   [2, 1, 0],
		Closing :   			[2, 1, 1],		
        Ivr :                   [2, 1, 2], 
        Waiting :               [2, 1, 3],
        Online :                [2, 1, 4], 
        WrapUp :                [2, 1, 5],
		Transfer :           	[2, 1, 6],		
		Overflowing :           [2, 1, 7],
		Preview :           	[2, 1, 8],
        RealTimeGraph :         [2, 1, 9]
    },  
    History : 
    {
        Dialled :                   [2, 2, 0],
        DialledTime :               [2, 2, 1], 
        EndInSystemProcessing :     [2, 2, 2],
        EndInSystemProcessingTime : [2, 2, 3], 
        EndInIvr :                  [2, 2, 4],
        EndInIvrTime :              [2, 2, 5],
        IvrFinish :                 [2, 2, 6],
        IvrFinishTime :             [2, 2, 7],
        IvrAbandoned :              [2, 2, 8],
        IvrAbandonedTime :          [2, 2, 9],
        Abandoned :                 [2, 2, 10],
        AbandonedTime :             [2, 2, 11],
        OverflowCount :             [2, 2, 12],
        OverflowContact :           [2, 2, 13],
        ToAgent :                   [2, 2, 14],
        ToAgentTime :               [2, 2, 15],
        Direct :                    [2, 2, 16],
        DirectTime :                [2, 2, 17],
        Waiting :                   [2, 2, 18],
        WaitingTime :               [2, 2, 19],
        Transfer :                  [2, 2, 20],
        TransferTime :              [2, 2, 21],
        ToAgentGraph :              [2, 2, 22],
        HistoryGraph :              [2, 2, 23]
    },
    Production : 
    {
        PositiveCount :     		[2, 3, 0],
        PositiveSum :       		[2, 3, 1],
        NegativeCount :     		[2, 3, 2],
        NegativeSum :       		[2, 3, 3],
        ArguedCount :    			[2, 3, 4],
        TotalQualified : 			[2, 3, 5],
        TotalNotQualified :  		[2, 3, 6],
		DialingActionTime :  		[2, 3, 7],
		DialingActionPosTime :  	[2, 3, 8],
		DialingActionNegTime :  	[2, 3, 9],
		DialingActionArgTime :  	[2, 3, 10],
		OnlineActionTime :  		[2, 3, 11],
		OnlineActionPosTime :  		[2, 3, 12],
		OnlineActionNegTime :  		[2, 3, 13],
		OnlineActionArgTime :  		[2, 3, 14],
		OnHoldActionTime :  		[2, 3, 15],
		OnHoldActionPosTime :  		[2, 3, 16],
		OnHoldActionNegTime :  		[2, 3, 17],
		OnHoldActionArgTime :  		[2, 3, 18],
		WrapUpActionTime :  		[2, 3, 19],
		WrapUpActionPosTime :  		[2, 3, 20],
		WrapUpActionNegTime :  		[2, 3, 21],
		WrapUpActionArgTime :		[2, 3, 22],
		CommunicationActionTime :  	[2, 3, 23],
		CommunicationActionPosTime :[2, 3, 24],
		CommunicationActionNegTime :[2, 3, 25],
		CommunicationActionArgTime :[2, 3, 26],
		WorkActionTime :  			[2, 3, 27],
		WorkActionPosTime :  		[2, 3, 28],
		WorkActionNegTime :  		[2, 3, 29],
		WorkActionArgTime :  		[2, 3, 30],
		CompletedContacts :  		[2, 3, 31],
		CompletedContactsTime :		[2, 3, 32],
		AvgArgComTime :  			[2, 3, 33],
		AvgArgWorkTime :  			[2, 3, 34],
		AvgPosComTime :  			[2, 3, 35],
		AvgPosWorkTime :  			[2, 3, 36],
		AvgNegComTime :  			[2, 3, 37],
		AvgNegWorkTime :  			[2, 3, 38],
        RatioTotQual_Tot :  		[2, 3, 39],
        RatioArg_Tot :      		[2, 3, 40],
        RatioArg_TotQual :  		[2, 3, 41],
        RatioPos_Tot :      		[2, 3, 42],
        RatioPos_TotQual :  		[2, 3, 43],
		RatioPos_Arg:				[2, 3, 44],
		RatioNeg_Tot:				[2, 3, 45],
		RatioNeg_TotQual:			[2, 3, 46],
		RationNeg_Arg:				[2, 3, 47],
		AvgPosValue:				[2, 3, 48],
		AvgNegValue:				[2, 3, 49],
		sys_Reset :  				[2, 3, 50],
		RatioTotQual_TotGraph :  	[2, 3, 51],
		RatioArg_TotQualGraph :  	[2, 3, 52],
		RatioPos_TotQualGraph :  	[2, 3, 53],
		RatioNeg_TotQualGraph :  	[2, 3, 54]

    },
    PeriodProduction : 
    {
        PositiveCount :     		[2, 4, 0],
        PositiveSum :       		[2, 4, 1],
        NegativeCount :     		[2, 4, 2],
        NegativeSum :       		[2, 4, 3],
        ArguedCount :    			[2, 4, 4],
        TotalQualified : 			[2, 4, 5],
        TotalNotQualified :  		[2, 4, 6],
		DialingActionTime :  		[2, 4, 7],
		DialingActionPosTime :  	[2, 4, 8],
		DialingActionNegTime :  	[2, 4, 9],
		DialingActionArgTime :  	[2, 4, 10],
		OnlineActionTime :  		[2, 4, 11],
		OnlineActionPosTime :  		[2, 4, 12],
		OnlineActionNegTime :  		[2, 4, 13],
		OnlineActionArgTime :  		[2, 4, 14],
		OnHoldActionTime :  		[2, 4, 15],
		OnHoldActionPosTime :  		[2, 4, 16],
		OnHoldActionNegTime :  		[2, 4, 17],
		OnHoldActionArgTime :  		[2, 4, 18],
		WrapUpActionTime :  		[2, 4, 19],
		WrapUpActionPosTime :  		[2, 4, 20],
		WrapUpActionNegTime :  		[2, 4, 21],
		WrapUpActionArgTime :		[2, 4, 22],
		CommunicationActionTime :  	[2, 4, 23],
		CommunicationActionPosTime :[2, 4, 24],
		CommunicationActionNegTime :[2, 4, 25],
		CommunicationActionArgTime :[2, 4, 26],
		WorkActionTime :  			[2, 4, 27],
		WorkActionPosTime :  		[2, 4, 28],
		WorkActionNegTime :  		[2, 4, 29],
		WorkActionArgTime :  		[2, 4, 30],
		CompletedContacts :  		[2, 4, 31],
		CompletedContactsTime :		[2, 4, 32],
		AvgArgComTime :  			[2, 4, 33],
		AvgArgWorkTime :  			[2, 4, 34],
		AvgPosComTime :  			[2, 4, 35],
		AvgPosWorkTime :  			[2, 4, 36],
		AvgNegComTime :  			[2, 4, 37],
		AvgNegWorkTime :  			[2, 4, 38],
        RatioTotQual_Tot :  		[2, 4, 39],
        RatioArg_Tot :      		[2, 4, 40],
        RatioArg_TotQual :  		[2, 4, 41],
        RatioPos_Tot :      		[2, 4, 42],
        RatioPos_TotQual :  		[2, 4, 43],
		RatioPos_Arg:				[2, 4, 44],
		RatioNeg_Tot:				[2, 4, 45],
		RatioNeg_TotQual:			[2, 4, 46],
		RationNeg_Arg:				[2, 4, 47],
		AvgPosValue:				[2, 4, 48],
		AvgNegValue:				[2, 4, 49],
		sys_Reset :  				[2, 4, 50],
		RatioTotQual_TotGraph :  	[2, 4, 51],
		RatioArg_TotQualGraph :  	[2, 4, 52],
		RatioPos_TotQualGraph :  	[2, 4, 53],
		RatioNeg_TotQualGraph :  	[2, 4, 54]

    },	
	ContactListInfo :
	{
		ContactCount :			[2, 5, 0],
		ContactToDial :			[2, 5, 1],
		ContactNeverDialed :	[2, 5, 2],
		ContactCallbacks :		[2, 5, 3],
		ContactToRedial :		[2, 5, 4],
		ContactToNotRedial : 	[2, 5, 5],
		ContactListGraph : 		[2, 5, 6]
	}
    
};
    
var Queue =  
{
    Parameters :
    {
        Id :            [3, 0, 0],
        Description :   [3, 0, 1], 
        GroupKey :      [3, 0, 2]
    },
    Realtime : 
    {
        Waiting :       [3, 1, 0],
        MaxWaiting  :   [3, 1, 1],
		AgentInReady  : [3, 1, 2]
    },
    History : 
    {
        Received :      		[3, 2, 0],
        ReceivedTime :  		[3, 2, 1],
        Processed :     		[3, 2, 2],
        ProcessedTime : 		[3, 2, 3],
        ProcessedDirect :     	[3, 2, 4],
        ProcessedDirectTime : 	[3, 2, 5],
        ProcessedWaiting :     	[3, 2, 6],
        ProcessedWaitingTime :	[3, 2, 7],
		ProcessedOverflow :		[3, 2, 8],
		ProcessedOverflowTime :	[3, 2, 9],
        Abandoned :     		[3, 2, 10],
        AbandonedTime : 		[3, 2, 11],				
        MaxQueueSize :  		[3, 2, 12],
        MaxWaitingTime :		[3, 2, 13],
        HistoryGraph :  		[3, 2, 14]
    }
};

var Team =
{
    Parameters :
    {
        Id :                [4, 0, 0],
        Description :       [4, 0, 1], 
        Group :             [4, 0, 2],
        Agents :            [4, 0, 3], 
        Queues :            [4, 0, 4], 
        AgentsLogonGraph :  [4, 0, 5]
    },
    Realtime : 
    {
        AgentsLogon :       [4, 1, 0],
        AgentsInPause :     [4, 1, 1], 
        AgentsInWaiting :   [4, 1, 2],
        AgentsOnline :      [4, 1, 3], 
        AgentsInWrapup :    [4, 1, 4],
        WaitingInQueue :    [4, 1, 5],
        RealTimeGraph :     [4, 1, 6]
        
    },
    Production : 
    {
        PositiveCount :     		[4, 3, 0],
        PositiveSum :       		[4, 3, 1],
        NegativeCount :     		[4, 3, 2],
        NegativeSum :       		[4, 3, 3],
        ArguedCount :    			[4, 3, 4],
        TotalQualified : 			[4, 3, 5],
        TotalNotQualified :  		[4, 3, 6],
		DialingActionTime :  		[4, 3, 7],
		DialingActionPosTime :  	[4, 3, 8],
		DialingActionNegTime :  	[4, 3, 9],
		DialingActionArgTime :  	[4, 3, 10],
		OnlineActionTime :  		[4, 3, 11],
		OnlineActionPosTime :  		[4, 3, 12],
		OnlineActionNegTime :  		[4, 3, 13],
		OnlineActionArgTime :  		[4, 3, 14],
		OnHoldActionTime :  		[4, 3, 15],
		OnHoldActionPosTime :  		[4, 3, 16],
		OnHoldActionNegTime :  		[4, 3, 17],
		OnHoldActionArgTime :  		[4, 3, 18],
		WrapUpActionTime :  		[4, 3, 19],
		WrapUpActionPosTime :  		[4, 3, 20],
		WrapUpActionNegTime :  		[4, 3, 21],
		WrapUpActionArgTime :		[4, 3, 22],
		CommunicationActionTime :  	[4, 3, 23],
		CommunicationActionPosTime :[4, 3, 24],
		CommunicationActionNegTime :[4, 3, 25],
		CommunicationActionArgTime :[4, 3, 26],
		WorkActionTime :  			[4, 3, 27],
		WorkActionPosTime :  		[4, 3, 28],
		WorkActionNegTime :  		[4, 3, 29],
		WorkActionArgTime :  		[4, 3, 30],
		CompletedContacts :  		[4, 3, 31],
		CompletedContactsTime :		[4, 3, 32],
		AvgArgComTime :  			[4, 3, 33],
		AvgArgWorkTime :  			[4, 3, 34],
		AvgPosComTime :  			[4, 3, 35],
		AvgPosWorkTime :  			[4, 3, 36],
		AvgNegComTime :  			[4, 3, 37],
		AvgNegWorkTime :  			[4, 3, 38],
        RatioTotQual_Tot :  		[4, 3, 39],
        RatioArg_Tot :      		[4, 3, 40],
        RatioArg_TotQual :  		[4, 3, 41],
        RatioPos_Tot :      		[4, 3, 42],
        RatioPos_TotQual :  		[4, 3, 43],
		RatioPos_Arg:				[4, 3, 44],
		RatioNeg_Tot:				[4, 3, 45],
		RatioNeg_TotQual:			[4, 3, 46],
		RationNeg_Arg:				[4, 3, 47],
		AvgPosValue:				[4, 3, 48],
		AvgNegValue:				[4, 3, 49],
		sys_Reset :  				[4, 3, 50],
		RatioTotQual_TotGraph :  	[4, 3, 51],
		RatioArg_TotQualGraph :  	[4, 3, 52],
		RatioPos_TotQualGraph :  	[4, 3, 53],
		RatioNeg_TotQualGraph :  	[4, 3, 54]

    },
    PeriodProduction : 
    {
        PositiveCount :     		[4, 4, 0],
        PositiveSum :       		[4, 4, 1],
        NegativeCount :     		[4, 4, 2],
        NegativeSum :       		[4, 4, 3],
        ArguedCount :    			[4, 4, 4],
        TotalQualified : 			[4, 4, 5],
        TotalNotQualified :  		[4, 4, 6],
		DialingActionTime :  		[4, 4, 7],
		DialingActionPosTime :  	[4, 4, 8],
		DialingActionNegTime :  	[4, 4, 9],
		DialingActionArgTime :  	[4, 4, 10],
		OnlineActionTime :  		[4, 4, 11],
		OnlineActionPosTime :  		[4, 4, 12],
		OnlineActionNegTime :  		[4, 4, 13],
		OnlineActionArgTime :  		[4, 4, 14],
		OnHoldActionTime :  		[4, 4, 15],
		OnHoldActionPosTime :  		[4, 4, 16],
		OnHoldActionNegTime :  		[4, 4, 17],
		OnHoldActionArgTime :  		[4, 4, 18],
		WrapUpActionTime :  		[4, 4, 19],
		WrapUpActionPosTime :  		[4, 4, 20],
		WrapUpActionNegTime :  		[4, 4, 21],
		WrapUpActionArgTime :		[4, 4, 22],
		CommunicationActionTime :  	[4, 4, 23],
		CommunicationActionPosTime :[4, 4, 24],
		CommunicationActionNegTime :[4, 4, 25],
		CommunicationActionArgTime :[4, 4, 26],
		WorkActionTime :  			[4, 4, 27],
		WorkActionPosTime :  		[4, 4, 28],
		WorkActionNegTime :  		[4, 4, 29],
		WorkActionArgTime :  		[4, 4, 30],
		CompletedContacts :  		[4, 4, 31],
		CompletedContactsTime :		[4, 4, 32],
		AvgArgComTime :  			[4, 4, 33],
		AvgArgWorkTime :  			[4, 4, 34],
		AvgPosComTime :  			[4, 4, 35],
		AvgPosWorkTime :  			[4, 4, 36],
		AvgNegComTime :  			[4, 4, 37],
		AvgNegWorkTime :  			[4, 4, 38],
        RatioTotQual_Tot :  		[4, 4, 39],
        RatioArg_Tot :      		[4, 4, 40],
        RatioArg_TotQual :  		[4, 4, 41],
        RatioPos_Tot :      		[4, 4, 42],
        RatioPos_TotQual :  		[4, 4, 43],
		RatioPos_Arg:				[4, 4, 44],
		RatioNeg_Tot:				[4, 4, 45],
		RatioNeg_TotQual:			[4, 4, 46],
		RationNeg_Arg:				[4, 4, 47],
		AvgPosValue:				[4, 4, 48],
		AvgNegValue:				[4, 4, 49],
		sys_Reset :  				[4, 4, 50],
		RatioTotQual_TotGraph :  	[4, 4, 51],
		RatioArg_TotQualGraph :  	[4, 4, 52],
		RatioPos_TotQualGraph :  	[4, 4, 53],
		RatioNeg_TotQualGraph :  	[4, 4, 54]

    }   		
};                  

var Campaign =
{
    Parameters :
    {
        Id :            [5, 0, 0],
        Description :   [5, 0, 1], 
        Group :         [5, 0, 2],
        Inbound :       [5, 0, 3], 
        InboundCount :  [5, 0, 4],
        Outbound :      [5, 0, 5], 
        OutboundCount : [5, 0, 6]    
    },
    Production : 
    {
        PositiveCount :     		[5, 3, 0],
        PositiveSum :       		[5, 3, 1],
        NegativeCount :     		[5, 3, 2],
        NegativeSum :       		[5, 3, 3],
        ArguedCount :    			[5, 3, 4],
        TotalQualified : 			[5, 3, 5],
        TotalNotQualified :  		[5, 3, 6],
		DialingActionTime :  		[5, 3, 7],
		DialingActionPosTime :  	[5, 3, 8],
		DialingActionNegTime :  	[5, 3, 9],
		DialingActionArgTime :  	[5, 3, 10],
		OnlineActionTime :  		[5, 3, 11],
		OnlineActionPosTime :  		[5, 3, 12],
		OnlineActionNegTime :  		[5, 3, 13],
		OnlineActionArgTime :  		[5, 3, 14],
		OnHoldActionTime :  		[5, 3, 15],
		OnHoldActionPosTime :  		[5, 3, 16],
		OnHoldActionNegTime :  		[5, 3, 17],
		OnHoldActionArgTime :  		[5, 3, 18],
		WrapUpActionTime :  		[5, 3, 19],
		WrapUpActionPosTime :  		[5, 3, 20],
		WrapUpActionNegTime :  		[5, 3, 21],
		WrapUpActionArgTime :		[5, 3, 22],
		CommunicationActionTime :  	[5, 3, 23],
		CommunicationActionPosTime :[5, 3, 24],
		CommunicationActionNegTime :[5, 3, 25],
		CommunicationActionArgTime :[5, 3, 26],
		WorkActionTime :  			[5, 3, 27],
		WorkActionPosTime :  		[5, 3, 28],
		WorkActionNegTime :  		[5, 3, 29],
		WorkActionArgTime :  		[5, 3, 30],
		CompletedContacts :  		[5, 3, 31],
		CompletedContactsTime :		[5, 3, 32],
		AvgArgComTime :  			[5, 3, 33],
		AvgArgWorkTime :  			[5, 3, 34],
		AvgPosComTime :  			[5, 3, 35],
		AvgPosWorkTime :  			[5, 3, 36],
		AvgNegComTime :  			[5, 3, 37],
		AvgNegWorkTime :  			[5, 3, 38],
        RatioTotQual_Tot :  		[5, 3, 39],
        RatioArg_Tot :      		[5, 3, 40],
        RatioArg_TotQual :  		[5, 3, 41],
        RatioPos_Tot :      		[5, 3, 42],
        RatioPos_TotQual :  		[5, 3, 43],
		RatioPos_Arg:				[5, 3, 44],
		RatioNeg_Tot:				[5, 3, 45],
		RatioNeg_TotQual:			[5, 3, 46],
		RationNeg_Arg:				[5, 3, 47],
		AvgPosValue:				[5, 3, 48],
		AvgNegValue:				[5, 3, 49],
		sys_Reset :  				[5, 3, 50],
		RatioTotQual_TotGraph :  	[5, 3, 51],
		RatioArg_TotQualGraph :  	[5, 3, 52],
		RatioPos_TotQualGraph :  	[5, 3, 53],
		RatioNeg_TotQualGraph :  	[5, 3, 54]
		
    },
    PeriodProduction : 
    {
        PositiveCount :     		[5, 4, 0],
        PositiveSum :       		[5, 4, 1],
        NegativeCount :     		[5, 4, 2],
        NegativeSum :       		[5, 4, 3],
        ArguedCount :    			[5, 4, 4],
        TotalQualified : 			[5, 4, 5],
        TotalNotQualified :  		[5, 4, 6],
		DialingActionTime :  		[5, 4, 7],
		DialingActionPosTime :  	[5, 4, 8],
		DialingActionNegTime :  	[5, 4, 9],
		DialingActionArgTime :  	[5, 4, 10],
		OnlineActionTime :  		[5, 4, 11],
		OnlineActionPosTime :  		[5, 4, 12],
		OnlineActionNegTime :  		[5, 4, 13],
		OnlineActionArgTime :  		[5, 4, 14],
		OnHoldActionTime :  		[5, 4, 15],
		OnHoldActionPosTime :  		[5, 4, 16],
		OnHoldActionNegTime :  		[5, 4, 17],
		OnHoldActionArgTime :  		[5, 4, 18],
		WrapUpActionTime :  		[5, 4, 19],
		WrapUpActionPosTime :  		[5, 4, 20],
		WrapUpActionNegTime :  		[5, 4, 21],
		WrapUpActionArgTime :		[5, 4, 22],
		CommunicationActionTime :  	[5, 4, 23],
		CommunicationActionPosTime :[5, 4, 24],
		CommunicationActionNegTime :[5, 4, 25],
		CommunicationActionArgTime :[5, 4, 26],
		WorkActionTime :  			[5, 4, 27],
		WorkActionPosTime :  		[5, 4, 28],
		WorkActionNegTime :  		[5, 4, 29],
		WorkActionArgTime :  		[5, 4, 30],
		CompletedContacts :  		[5, 4, 31],
		CompletedContactsTime :		[5, 4, 32],
		AvgArgComTime :  			[5, 4, 33],
		AvgArgWorkTime :  			[5, 4, 34],
		AvgPosComTime :  			[5, 4, 35],
		AvgPosWorkTime :  			[5, 4, 36],
		AvgNegComTime :  			[5, 4, 37],
		AvgNegWorkTime :  			[5, 4, 38],
        RatioTotQual_Tot :  		[5, 4, 39],
        RatioArg_Tot :      		[5, 4, 40],
        RatioArg_TotQual :  		[5, 4, 41],
        RatioPos_Tot :      		[5, 4, 42],
        RatioPos_TotQual :  		[5, 4, 43],
		RatioPos_Arg:				[5, 4, 44],
		RatioNeg_Tot:				[5, 4, 45],
		RatioNeg_TotQual:			[5, 4, 46],
		RationNeg_Arg:				[5, 4, 47],
		AvgPosValue:				[5, 4, 48],
		AvgNegValue:				[5, 4, 49],
		sys_Reset :  				[5, 3, 50],
		RatioTotQual_TotGraph :  	[5, 3, 51],
		RatioArg_TotQualGraph :  	[5, 3, 52],
		RatioPos_TotQualGraph :  	[5, 3, 53],
		RatioNeg_TotQualGraph :  	[5, 3, 54]

    },	
	ContactListInfo :
	{
		ContactCount :			[5, 5, 0],
		ContactToDial :			[5, 5, 1],
		ContactNeverDialed :	[5, 5, 2],
		ContactCallbacks :		[5, 5, 3],
		ContactToRedial :		[5, 5, 4],
		ContactToNotRedial : 	[5, 5, 5]
	}
};                    
    
var Enums =
{
    operators :
    {
        //Relational
        '0' : 'E',      //equal
        '1' : 'nE',     //not equal
        '2' : 'GoE',    //greater than or equal
        '3' : 'LoE',    //less than or equal
        '4' : 'G',      //greater than
        '5' : 'L',      //less than
        
        'E'     : 0,
        'nE'    : 1,
        'GoE'   : 2,
        'LoE'   : 3,
        'G'     : 4,
        'L'     : 5
    },
    
    filterOriginator :
    {
        '0' : 'System',
        '1' : 'User',
        
        'System'    : 0,
        'User'      : 1
    },
    
    model : 
    { 
        types : 
        { 
            '0' : 'Agent', 
            '1' : 'Inbound', 
            '2' : 'Outbound', 
            '3' : 'Queue',
            '4' : 'team',
            '5' : 'campaign', 

            'Agent'     : 0, 
            'Inbound'   : 1, 
            'Outbound'  : 2, 
            'Queue'     : 3,
            'team'      : 4, 
            'campaign'  : 5
        },
        
        keys :
        {
            '0' : 'Parameters', 
            '1' : 'RealTime', 
            '2' : 'History',
            '3' : 'Production',
			'4' : 'PeriodProduction',
			'5' : 'ContactListInfo',
            '6' : 'SystemColumns',
            '7' : 'UserColumns',
            '8' : 'PeakParameters', 
            '9' : 'PeakRealTime', 
            '10' : 'PeakHistory', 
            '11' : 'PeakProduction', 

            'Parameters'        : 0, 
            'RealTime'          : 1, 
            'History'           : 2,
            'Production'        : 3,
			'PeriodProduction'	: 4,
			'ContactListInfo'   : 5,
            'SystemColumns'     : 6, 
            'UserColumns'       : 7,             
            'PeakParameters'    : 8, 
            'PeakRealTime'      : 9, 
            'PeakHistory'       : 10,
            'PeakProduction'    : 11
        },

        agentState :
        { 
            '1' : 'off', 
            '2' : 'Loging', 
            '3' : 'Pause', 
            '4' : 'Waiting', 
            '5' : 'Online', 
            '6' : 'Wrapup', 
            '7' : 'Logout', 
			'8' : 'Supervision',

            'off' : 1, 
            'Loging' : 2, 
            'Pause' : 3,
            'Waiting' : 4, 
            'Online' : 5, 
            'Wrapup' : 6,
            'Logout' : 7,
			'Supervision' : 8
        },
              
        outboundMode :
        { 
            '0' : 'Undefined', 
            '1' : 'CallbacksOnly', 
            '2' : 'Preview', 
            '3' : 'Progressive', 
            '4' : 'Power', 
            '5' : 'Predictive', 
            '6' : 'Fixed', 
            '7' : 'RestrictedPower', 
                        
            'Undefined'         : 0, 
            'CallbacksOnly'     : 1, 
            'Preview'           : 2,
            'Progressive'       : 3,
            'Power'             : 4, 
            'Predictive'        : 5, 
            'Fixed'             : 6,
            'RestrictedPower'   : 7            
        }
    },
    
    column :
    {
        type :
        {
            '0' : 'Value', 
            '1' : 'Graph', 
            '2' : 'List',
            '3' : 'Formula',
			'4' : 'GraphPercent',
			'5' : 'DateTime',
            
            'Value' : 0, 
            'Graph' : 1,
            'List' : 2,
            'Formula' : 3,
			'GraphPercent' : 4,
			'DateTime' : 5
        },
        
        style :
        { 
            '0' : 'Text', 
            '1' : 'Numeric', 
            '2' : 'Time',
            '3' : 'Percent',
            '4' : 'GraphBar',
            '5' : 'Count',
			'6' : 'Float',
			'7' : 'Timer',
			'8' : 'DateTime',

            'Text' : 0, 
            'Numeric' : 1,
            'Time' : 2,
            'Percent' : 3,
            'GraphBar' : 4,
            'Count' : 5,
			'Float' : 6,
			'Timer' : 7,
			'DateTime' : 8
        },
        panel :
        { 
            '0' : 'Detail', 
            '1' : 'Graph',
            '2' : 'FieldHistory', 
            '3' : 'List', 

            'Detail' : 0, 
            'Graph' : 1,
            'FieldHistory' : 2,
            'List' : 3
        }
    }
};